(senny-make-theme "Github"
                  ((background-color . "#f8f8ff")
                   (background-mode . light)
                   (border-color . "black")
                   (cursor-color . "#000000")
                   (foreground-color . "#000000")
                   (mouse-color . "#bcd5fa"))
                  :base-font          (:stipple nil :background "#f8f8ff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal)
                  :selection          (:background "#bcd5fa")
                  :brief-highlight    (:background "#acc3e6")
                  :durable-highlight  (:background "#dddddd")
                  :link               (:foreground "blue1" :underline t)
                  :mode-line          (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :height 0.85)
                  :minibuffer-prompt  (:foreground "#445588")
                  :code-variable      (:foreground "#0086b3")
                  :code-reference     (nil)
                  :code-constant      (:foreground "#990073")
                  :code-type          (:foreground "#445588")
                  :code-keyword       (:bold t :weight bold)
                  :code-string        (:foreground "#dd1144")
                  :code-comment       (:italic t :foreground "#999988" :slant italic)
                  :code-documentation (:foreground "#dd1144")
                  :code-function      (:foreground "#990000")
                  :code-meta          (:foreground "Aquamarine")
                  :code-error         (:background "#dd1144")
                  :code-warning       (:background "#4A410D")
                  :code-info          (:background "#fff6a9")
                  :code-addition      (:background "#253B22")
                  :code-escape-char   (:foreground "#009926"))

     ;; (css-property ((t (:foreground "#0086b3"))))
     ;; (css-selector ((t (:foreground "#990000"))))
     ;; (cursor ((t (:background "#a7a7a7"))))
     ;; (ecb-default-general-face ((t (:height 0.9))))
     ;; (ecb-default-highlight-face ((t (:background "#bcd5fa" :foreground "#000000"))))
     ;; (ecb-directories-general-face ((t (:bold t :weight bold))))
     ;; (ecb-source-in-directories-buffer-face ((t (:foreground "#445588"))))
     ;; (erb-comment-delim-face ((t (:italic t :bold t :slant italic :foreground "#999988" :weight bold))))
     ;; (erb-comment-face ((t (:bold t :background "#eeeeee" :foreground "#999988" :weight bold))))
     ;; (erb-delim-face ((t (:bold t :weight bold))))
     ;; (erb-exec-delim-face ((t (:bold t :weight bold))))
     ;; (erb-exec-face ((t (:background "#eeeeee"))))
     ;; (erb-face ((t (:background "#eeeeee"))))
     ;; (erb-out-delim-face ((t (:bold t :foreground "#445588" :weight bold))))
     ;; (erb-out-face ((t (:background "#eeeeee"))))

     ;; (font-lock-regexp-grouping-construct ((t (:foreground "#009926"))))

     ;; (link-visited ((t (:underline t :foreground "magenta4"))))
     ;; (mouse ((t (:background "#bcd5fa"))))
     ;; (quack-about-face ((t (:family "Helvetica"))))
     ;; (quack-about-title-face ((t (:bold t :foreground "#008000" :weight bold :height 2.0 :family "Helvetica"))))
     ;; (quack-banner-face ((t (:family "Helvetica"))))
     ;; (quack-pltfile-dir-face ((t (:bold t :background "gray33" :foreground "white" :weight bold :height 1.2 :family "Helvetica"))))
     ;; (quack-pltfile-file-face ((t (:bold t :background "gray66" :foreground "black" :weight bold :height 1.2 :family "Helvetica"))))
     ;; (quack-pltfile-prologue-face ((t (:background "gray66" :foreground "black"))))
     ;; (quack-pltish-class-defn-face ((t (:bold t :weight bold :foreground "purple3"))))
     ;; (quack-pltish-comment-face ((t (:foreground "cyan4"))))
     ;; (quack-pltish-defn-face ((t (:bold t :foreground "blue3" :weight bold))))
     ;; (quack-pltish-keyword-face ((t (:bold t :weight bold))))
     ;; (quack-pltish-module-defn-face ((t (:bold t :weight bold :foreground "purple3"))))
     ;; (quack-pltish-paren-face ((t (:foreground "red3"))))
     ;; (quack-pltish-selfeval-face ((t (:foreground "green4"))))
     ;; (quack-smallprint-face ((t (:height 0.8 :family "Courier"))))
     ;; (quack-threesemi-h1-face ((t (:bold t :weight bold :height 1.4 :family "Helvetica"))))
     ;; (quack-threesemi-h2-face ((t (:bold t :weight bold :height 1.2 :family "Helvetica"))))
     ;; (quack-threesemi-h3-face ((t (:bold t :weight bold :family "Helvetica"))))
     ;; (quack-threesemi-semi-face ((t (:background "#c0ffff" :foreground "#a0ffff"))))
     ;; (quack-threesemi-text-face ((t (:background "#c0ffff" :foreground "cyan4"))))

