(eval-when-compile (require 'color-theme))
(defun color-theme-github ()
  "Color theme by Dudley Flanders, created 2008-07-11."
  (interactive)
  (color-theme-install
   '(color-theme-github
     ((background-color . "#f8f8ff")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "#000000")
      (foreground-color . "#000000")
      (mouse-color . "#bcd5fa"))
     ()
     ;; TODO: Change the Aquamarine color
     (preprocessor ((t (:foreground "Aquamarine"))))
     (highlighted ((t (:background "#acc3e6"))))
     (highlighted-line ((t (:background "#DBDBDB"))))
     (flashy-highlight ((t (:background "#F9FF85"))))
     (default ((t (:stipple nil :background "#f8f8ff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal))))
     (variable ((t (:foreground "#108088"))))
     (constant ((t (:foreground "#990073"))))
     (type ((t (:foreground "#445588"))))
     (keyword ((t (:bold t :weight bold))))
     (string ((t (:foreground "#dd1144"))))
     (comment ((t (:italic t :foreground "#999988" :slant italic))))
     (doc ((t (:foreground "#999988"))))
     (function-def ((t (:foreground "#990000"))))
     (code-error ((t (:underline t :inherit diff-removed))))
     (code-warning ((t (:underline t :inherit diff-changed))))
     (menu ((t (:background "darkgrey"))))

     (ac-menu-face ((t (:inherit menu))))
     (ac-selection-face ((t (:inherit flashy-highlight))))
     (ac-dabbrev-menu-face ((t (:inherit menu))))
     (ac-dabbrev-selection-face ((t (:inherit highlighted))))
     
     (diff-header ((t (:inherit default :background "#CCCCFF"))))
     (diff-added ((t (:inherit default :background "#CCFFCC"))))
     (diff-removed ((t (:inherit default :background "#FFCCCC"))))
     (diff-changed ((t (:inherit default :background "#FFFFCC"))))

     ;;      TODO: Add support for ancestor highlighting
     (ediff-current-diff-A ((t (:background "#FFDDDD"))))
     (ediff-current-diff-B ((t (:background "#DDFFDD" ))))
     (ediff-current-diff-C ((t (:background "#DDDDFF" ))))
     ;;      (ediff-current-diff-Ancestor ((t (:background "#BBFFBB"))))
     (ediff-fine-diff-A ((t (:inherit default :underline t :background "#FF8888"))))
     (ediff-fine-diff-B ((t (:inherit default :underline t :background "#88FF88"))))
     (ediff-fine-diff-C ((t (:inherit default :underline t :background "#8888FF"))))
     ;;      (ediff-fine-diff-Ancestor ((t (:underline t :background "#0B5C00" ))))
     (ediff-even-diff-A ((t (:background "#E0E0E0"))))
     (ediff-even-diff-B ((t (:background "#E0E0E0"))))
     (ediff-even-diff-C ((t (:background "#E0E0E0"))))
     ;;      (ediff-even-diff-Ancestor ((t (:background "#E0E0E0"))))
     (ediff-odd-diff-A ((t (:background "#E0E0E0"))))
     (ediff-odd-diff-B ((t (:background "#E0E0E0"))))
     (ediff-odd-diff-C ((t (:background "#E0E0E0"))))
     ;;      (ediff-odd-diff-Ancestor ((t (:background "#E0E0E0"))))     
     
     (cursor ((t (:background "#a7a7a7"))))

     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (minibuffer-prompt ((t (:foreground "#445588"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mouse ((t (:inherit region))))
     (region ((t (:background "#bcd5fa"))))
     (show-paren-match ((t (:inherit diff-header))))
     (show-paren-mismatch ((t (:inherit diff-removed)))))))
(add-to-list 'color-themes '(color-theme-github  "GitHub" "Dudley Flanders"))
